VOYAGE-266: added new mc teamplates per design
Backbase/engagements-data pull request #33
Opened 2023-07-17 09:25 UTC by echonax

2023-07-17 09:36 UTC, eacarvalho requested changes

2023-07-17 09:36 UTC, eacarvalho commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/thumbnail.png
Please are you sure this is a thumbnail? Looks like this is the image of the template because the size is 1048x1222.

2023-07-17 09:36 UTC, eacarvalho commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/apple-pay.png
Please why all the template images were removed?

2023-07-17 09:36 UTC, eacarvalho commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/content-schema.json
> +          "default":"{{contextRoot}}/assets/dark.png",
I don't see this `dark.png` in the assets folder. Did you test it in the internal repository?

2023-07-17 09:36 UTC, eacarvalho commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/index.html
Btw will also change for Business Banking or only Retail?

2023-07-17 09:37 UTC, echonax commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/thumbnail.png
yeh Myles wanted it that way for now and will be revisited later apparently :(

2023-07-17 09:38 UTC, echonax commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/apple-pay.png
they're replaced by dark and light pngs but you're right i also don't see them

2023-07-17 09:50 UTC, eacarvalho commented on collections/retail/custom-engagements/templates/apple-pay-launch-template/assets/thumbnail.png
Are you sure this is the correct approach? Reach him out again and why not apply now the correct solution? cc @DenysShmyhin

2023-07-17 14:46 UTC, eacarvalho commented
@echonax probably you will also change the images size in this repo, right?

2023-07-21 13:14 UTC, madz0 approved these changes

2023-07-21 14:17 UTC, eacarvalho requested changes

2023-07-21 14:17 UTC, eacarvalho commented on collections/business/custom-engagements/templates/blank-template/assets/index.html
@madz0 and @echonax since this is a new folder for Business Banking please check if the packages are being created correctly for Business Banking and copied to the docker image.

```
https://github.com/Backbase/engagements-data/blob/master/ci/scripts/create-collections.sh
```

2023-07-21 14:29 UTC, merged

2023-07-21 15:22 UTC, eacarvalho commented
Did you test the packages per my comment?

2023-07-21 15:30 UTC, madz0 commented
> Did you test the packages per my comment?

@echonax informed me he has resolved everything about the comments